// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.data;

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210505233446_4_migracao")]
    partial class _4_migracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("backend.models.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("InvestimentoDiario")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Anuncio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DataInicio = new DateTime(2021, 5, 5, 20, 34, 45, 453, DateTimeKind.Local).AddTicks(4342),
                            DataTermino = new DateTime(2021, 6, 4, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(2365),
                            InvestimentoDiario = 1.0,
                            Nome = "Anuncio1"
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            DataInicio = new DateTime(2021, 5, 6, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(8264),
                            DataTermino = new DateTime(2021, 6, 4, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(8291),
                            InvestimentoDiario = 2.0,
                            Nome = "Anuncio 2"
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 1,
                            DataInicio = new DateTime(2021, 5, 7, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(8301),
                            DataTermino = new DateTime(2021, 6, 4, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(8304),
                            InvestimentoDiario = 3.0,
                            Nome = "Anuncio 3"
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 1,
                            DataInicio = new DateTime(2021, 5, 8, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(8308),
                            DataTermino = new DateTime(2021, 6, 4, 20, 34, 45, 455, DateTimeKind.Local).AddTicks(8310),
                            InvestimentoDiario = 1.0,
                            Nome = "Anuncio 2"
                        });
                });

            modelBuilder.Entity("backend.models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Darlan"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vanessa"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Nicolas"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Gabriel"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Gengis"
                        });
                });

            modelBuilder.Entity("backend.models.Anuncio", b =>
                {
                    b.HasOne("backend.models.Cliente", "Cliente")
                        .WithMany("Anuncios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backend.models.Cliente", b =>
                {
                    b.Navigation("Anuncios");
                });
#pragma warning restore 612, 618
        }
    }
}
